### ISSUE TITLE
Feature Request: Set reminder

### ISSUE THREAD

**Issue by willisra** [ja2375/add_2_calendar#36]
Hi,

first of all, I'm already thankful for the work you have put in the component, but it would be very beneficial to be able to set a reminder at some user-defined time before the event... 

Thanks!

**Comment by furkankurt** [comment]
I couldn't solve on android, but I solved on iOS side. You can use my branch #44

**Comment by furkankurt** [comment]
You can use like this for now.
```
  add_2_calendar:
    git:
      url: https://github.com/furkankurt/add_2_calendar
      ref: alert_for_ios
```
